CREATE TABLE IF NOT EXISTS billing_rules (
    id VARCHAR(64) PRIMARY KEY,
    global_model_id VARCHAR(64),
    model_id VARCHAR(64),
    name VARCHAR(255) NOT NULL,
    task_type VARCHAR(64) NOT NULL DEFAULT 'chat',
    expression TEXT NOT NULL,
    variables TEXT NOT NULL,
    dimension_mappings TEXT NOT NULL,
    is_enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    KEY billing_rules_global_model_task_idx (global_model_id, task_type, is_enabled),
    KEY billing_rules_model_task_idx (model_id, task_type, is_enabled)
);

CREATE TABLE IF NOT EXISTS dimension_collectors (
    id VARCHAR(64) PRIMARY KEY,
    api_format VARCHAR(64) NOT NULL,
    task_type VARCHAR(64) NOT NULL,
    dimension_name VARCHAR(128) NOT NULL,
    source_type VARCHAR(64) NOT NULL,
    source_path VARCHAR(255),
    value_type VARCHAR(64) NOT NULL DEFAULT 'float',
    transform_expression TEXT,
    default_value VARCHAR(255),
    priority INT NOT NULL DEFAULT 0,
    is_enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    KEY dimension_collectors_enabled_idx (
        api_format,
        task_type,
        dimension_name,
        priority,
        is_enabled
    )
);

CREATE TABLE IF NOT EXISTS providers (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    website VARCHAR(500),
    provider_type VARCHAR(64) NOT NULL,
    billing_type VARCHAR(64),
    monthly_quota_usd DOUBLE,
    monthly_used_usd DOUBLE,
    quota_reset_day INT,
    quota_last_reset_at BIGINT,
    quota_expires_at BIGINT,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    priority BIGINT NOT NULL DEFAULT 0,
    provider_priority INT NOT NULL DEFAULT 100,
    keep_priority_on_conversion TINYINT(1) NOT NULL DEFAULT 0,
    enable_format_conversion TINYINT(1) NOT NULL DEFAULT 1,
    concurrent_limit INT,
    max_retries INT,
    proxy TEXT,
    request_timeout DOUBLE,
    stream_first_byte_timeout DOUBLE,
    config TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    UNIQUE KEY providers_name_key (name)
);

CREATE TABLE IF NOT EXISTS provider_api_keys (
    id VARCHAR(64) PRIMARY KEY,
    provider_id VARCHAR(64) NOT NULL,
    name VARCHAR(255) NOT NULL,
    api_key TEXT,
    encrypted_key TEXT,
    auth_type VARCHAR(32) NOT NULL DEFAULT 'api_key',
    auth_config TEXT,
    note TEXT,
    internal_priority INT NOT NULL DEFAULT 50,
    capabilities TEXT,
    api_formats TEXT,
    auth_type_by_format TEXT,
    allow_auth_channel_mismatch_formats TEXT,
    rate_multipliers TEXT,
    global_priority_by_format TEXT,
    allowed_models TEXT,
    expires_at BIGINT,
    cache_ttl_minutes INT NOT NULL DEFAULT 5,
    max_probe_interval_minutes INT NOT NULL DEFAULT 32,
    proxy TEXT,
    fingerprint TEXT,
    concurrent_limit INT,
    learned_rpm_limit INT,
    concurrent_429_count INT NOT NULL DEFAULT 0,
    rpm_429_count INT NOT NULL DEFAULT 0,
    last_429_at BIGINT,
    last_429_type VARCHAR(64),
    adjustment_history TEXT,
    utilization_samples TEXT,
    last_probe_increase_at BIGINT,
    last_rpm_peak INT,
    request_count BIGINT NOT NULL DEFAULT 0,
    total_tokens BIGINT NOT NULL DEFAULT 0,
    total_cost_usd DOUBLE NOT NULL DEFAULT 0,
    success_count BIGINT NOT NULL DEFAULT 0,
    error_count BIGINT NOT NULL DEFAULT 0,
    total_response_time_ms BIGINT NOT NULL DEFAULT 0,
    last_used_at BIGINT,
    auto_fetch_models TINYINT(1) NOT NULL DEFAULT 0,
    last_models_fetch_at BIGINT,
    last_models_fetch_error TEXT,
    locked_models TEXT,
    model_include_patterns TEXT,
    model_exclude_patterns TEXT,
    upstream_metadata TEXT,
    oauth_invalid_at BIGINT,
    oauth_invalid_reason VARCHAR(255),
    status_snapshot TEXT,
    health_by_format TEXT,
    circuit_breaker_by_format TEXT,
    status VARCHAR(64) NOT NULL DEFAULT 'active',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    weight BIGINT NOT NULL DEFAULT 1,
    rpm_limit BIGINT,
    metadata TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    KEY provider_api_keys_provider_id_idx (provider_id),
    KEY idx_provider_api_keys_provider_default_sort (provider_id, internal_priority, name, id)
);

CREATE TABLE IF NOT EXISTS pool_member_scores (
    id VARCHAR(192) PRIMARY KEY,
    pool_kind VARCHAR(64) NOT NULL,
    pool_id VARCHAR(64) NOT NULL,
    member_kind VARCHAR(64) NOT NULL,
    member_id VARCHAR(64) NOT NULL,
    capability VARCHAR(64) NOT NULL,
    scope_kind VARCHAR(64) NOT NULL,
    scope_id VARCHAR(128),
    score DOUBLE NOT NULL DEFAULT 0,
    hard_state VARCHAR(64) NOT NULL DEFAULT 'unknown',
    score_version BIGINT NOT NULL DEFAULT 1,
    score_reason TEXT NOT NULL,
    last_ranked_at BIGINT,
    last_scheduled_at BIGINT,
    last_success_at BIGINT,
    last_failure_at BIGINT,
    failure_count BIGINT NOT NULL DEFAULT 0,
    last_probe_attempt_at BIGINT,
    last_probe_success_at BIGINT,
    last_probe_failure_at BIGINT,
    probe_failure_count BIGINT NOT NULL DEFAULT 0,
    probe_status VARCHAR(64) NOT NULL DEFAULT 'never',
    updated_at BIGINT NOT NULL,
    KEY pool_member_scores_rank_idx (pool_kind, pool_id, capability, scope_kind, scope_id, hard_state, score DESC),
    KEY pool_member_scores_member_idx (pool_kind, pool_id, member_kind, member_id),
    KEY pool_member_scores_probe_idx (pool_kind, pool_id, probe_status, last_probe_success_at),
    KEY pool_member_scores_updated_at_idx (updated_at)
);

CREATE TABLE IF NOT EXISTS gemini_file_mappings (
    id VARCHAR(64) PRIMARY KEY,
    file_name VARCHAR(512) NOT NULL,
    key_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64),
    display_name VARCHAR(512),
    mime_type VARCHAR(255),
    source_hash VARCHAR(128),
    created_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    UNIQUE KEY gemini_file_mappings_file_name_key (file_name),
    KEY gemini_file_mappings_key_id_idx (key_id),
    KEY gemini_file_mappings_user_id_idx (user_id),
    KEY gemini_file_mappings_expires_at_idx (expires_at),
    KEY gemini_file_mappings_source_hash_idx (source_hash)
);

CREATE TABLE IF NOT EXISTS request_candidates (
    id VARCHAR(64) PRIMARY KEY,
    request_id VARCHAR(128) NOT NULL,
    user_id VARCHAR(64),
    api_key_id VARCHAR(64),
    username VARCHAR(255),
    api_key_name VARCHAR(255),
    candidate_index INT NOT NULL,
    retry_index INT NOT NULL DEFAULT 0,
    provider_id VARCHAR(64),
    endpoint_id VARCHAR(64),
    key_id VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    skip_reason TEXT,
    is_cached TINYINT(1) NOT NULL DEFAULT 0,
    status_code INT,
    error_type VARCHAR(128),
    error_message TEXT,
    latency_ms INT,
    concurrent_requests INT,
    extra_data TEXT,
    required_capabilities TEXT,
    created_at BIGINT NOT NULL,
    started_at BIGINT,
    finished_at BIGINT,
    UNIQUE KEY uq_request_candidate_with_retry (request_id, candidate_index, retry_index),
    KEY request_candidates_request_id_idx (request_id),
    KEY request_candidates_provider_id_idx (provider_id),
    KEY request_candidates_endpoint_id_idx (endpoint_id),
    KEY request_candidates_status_idx (status),
    KEY request_candidates_created_at_idx (created_at),
    KEY request_candidates_endpoint_status_created_idx (endpoint_id, status, created_at)
);

CREATE TABLE IF NOT EXISTS video_tasks (
    id VARCHAR(64) PRIMARY KEY,
    short_id VARCHAR(32),
    request_id VARCHAR(128) NOT NULL,
    user_id VARCHAR(64),
    api_key_id VARCHAR(64),
    username VARCHAR(255),
    api_key_name VARCHAR(255),
    external_task_id VARCHAR(255),
    provider_id VARCHAR(64),
    endpoint_id VARCHAR(64),
    key_id VARCHAR(64),
    client_api_format VARCHAR(128),
    provider_api_format VARCHAR(128),
    format_converted TINYINT(1) NOT NULL DEFAULT 0,
    model VARCHAR(255),
    prompt TEXT,
    original_request_body TEXT,
    duration_seconds INT,
    resolution VARCHAR(64),
    aspect_ratio VARCHAR(32),
    size VARCHAR(64),
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    progress_percent INT NOT NULL DEFAULT 0,
    progress_message TEXT,
    retry_count INT NOT NULL DEFAULT 0,
    poll_interval_seconds INT NOT NULL DEFAULT 10,
    next_poll_at BIGINT,
    poll_count INT NOT NULL DEFAULT 0,
    max_poll_count INT NOT NULL DEFAULT 360,
    created_at BIGINT NOT NULL,
    submitted_at BIGINT,
    completed_at BIGINT,
    updated_at BIGINT NOT NULL,
    error_code VARCHAR(128),
    error_message TEXT,
    video_url TEXT,
    request_metadata TEXT,
    UNIQUE KEY video_tasks_short_id_key (short_id),
    UNIQUE KEY video_tasks_request_id_key (request_id),
    KEY video_tasks_external_id_idx (external_task_id),
    KEY video_tasks_next_poll_idx (next_poll_at),
    KEY video_tasks_user_status_idx (user_id, status),
    KEY video_tasks_api_key_id_idx (api_key_id),
    KEY video_tasks_provider_id_idx (provider_id),
    KEY video_tasks_endpoint_id_idx (endpoint_id),
    KEY video_tasks_key_id_idx (key_id)
);

CREATE TABLE IF NOT EXISTS provider_endpoints (
    id VARCHAR(64) PRIMARY KEY,
    provider_id VARCHAR(64) NOT NULL,
    name VARCHAR(255) NOT NULL,
    base_url TEXT NOT NULL,
    api_format VARCHAR(128),
    api_family VARCHAR(128),
    endpoint_kind VARCHAR(128),
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    health_score DOUBLE NOT NULL DEFAULT 1.0,
    weight BIGINT NOT NULL DEFAULT 1,
    header_rules TEXT,
    body_rules TEXT,
    max_retries INT,
    custom_path TEXT,
    metadata TEXT,
    config TEXT,
    format_acceptance_config TEXT,
    proxy TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    KEY provider_endpoints_provider_id_idx (provider_id)
);

CREATE TABLE IF NOT EXISTS models (
    id VARCHAR(64) PRIMARY KEY,
    provider_id VARCHAR(64) NOT NULL,
    global_model_id VARCHAR(64),
    provider_model_name VARCHAR(255) NOT NULL,
    global_model_name VARCHAR(255),
    api_format VARCHAR(128),
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_available TINYINT(1) NOT NULL DEFAULT 1,
    price_per_request DOUBLE,
    tiered_pricing TEXT,
    supports_vision TINYINT(1),
    supports_function_calling TINYINT(1),
    supports_streaming TINYINT(1),
    supports_extended_thinking TINYINT(1),
    supports_image_generation TINYINT(1),
    provider_model_mappings TEXT,
    config TEXT,
    metadata TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    KEY models_provider_id_idx (provider_id)
);

CREATE TABLE IF NOT EXISTS global_models (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    default_price_per_request DOUBLE,
    default_tiered_pricing TEXT,
    supported_capabilities TEXT,
    usage_count BIGINT NOT NULL DEFAULT 0,
    config TEXT,
    metadata TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    UNIQUE KEY global_models_name_key (name)
);
