//! MySQL pool adapter primitives.

mod announcements;
mod audit;
mod auth;
mod auth_modules;
mod background_tasks;
mod billing;
mod candidate_selection;
mod candidates;
mod error;
mod gemini_file_mappings;
mod global_models;
mod management_tokens;
mod migrations;
mod oauth_providers;
mod pool;
mod pool_scores;
mod provider_catalog;
mod proxy_nodes;
mod quota;
mod routing_profiles;
mod settlement;
mod usage;
mod users;
mod video_tasks;
mod wallet;

pub use aether_data_contracts::{DataLayerError, DatabaseDriver, SqlDatabaseConfig, SqlPoolConfig};
pub use announcements::MysqlAnnouncementRepository;
pub use audit::MysqlAuditLogReadRepository;
pub use auth::MysqlAuthApiKeyReadRepository;
pub use auth_modules::{MysqlAuthModuleReadRepository, MysqlAuthModuleRepository};
pub use background_tasks::MysqlBackgroundTaskRepository;
pub use billing::MysqlBillingReadRepository;
pub use candidate_selection::MysqlMinimalCandidateSelectionReadRepository;
pub use candidates::MysqlRequestCandidateRepository;
pub use gemini_file_mappings::MysqlGeminiFileMappingRepository;
pub use global_models::MysqlGlobalModelReadRepository;
pub use management_tokens::MysqlManagementTokenRepository;
pub use migrations::{pending_migrations, prepare_database_for_startup, run_migrations, MIGRATOR};
pub use oauth_providers::MysqlOAuthProviderRepository;
pub use pool::{MysqlPool, MysqlPoolConfig, MysqlPoolFactory};
pub use pool_scores::MysqlPoolMemberScoreRepository;
pub use provider_catalog::MysqlProviderCatalogReadRepository;
pub use proxy_nodes::MysqlProxyNodeReadRepository;
pub use quota::MysqlProviderQuotaRepository;
pub use routing_profiles::MysqlRoutingGroupRepository;
pub use settlement::MysqlSettlementRepository;
pub use usage::{MysqlUsageStorage, MysqlUsageWriteRepository};
pub use users::MysqlUserReadRepository;
pub use video_tasks::MysqlVideoTaskRepository;
pub use wallet::MysqlWalletReadRepository;
